# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: alkemio
  font: alkemio
  font_size: L

# SEO

marketing:
  seo:
    site_type: organization
    local_business_type: ''
    org_name: 'Alkemio'
    description: 'A new way of working on Challenges, together.'
    twitter: 'Alkem_io'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''


header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# Site footer - Turn enable to true to turn on again - See partials for current footer.

footer:
  block: alkemio-footer

# Localization

locale:
  date_format: '2 January 2006'
  time_format: '15:04'
  address_format: nl

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/alkem-io/website'
    content_dir: content
    branch: develop
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true



